### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by JandersonConstantino** [rodrigowernke/Teste-Bludata#1]
Bom dia Rodrigo,
Poderia remover dessa linha para baixo do arquivo .gitignore e fazer um novo commit para subir os arquivos faltantes?
o repositório veio sem solution e outros arquivos.

https://github.com/rodrigowernke/Teste-Bludata/blob/6c464efce9056f7a0adaedd5f88c8664e6271821/.gitignore#L262

**Comment by rodrigowernke** [comment]
Boa noite Jarderson, fiz a alteração que você pediu.
